server:
  port: 8081

spring:
  application:
    name: steamwishlist-monitor
  mail:
    host: smtp.gmail.com
    port: 587
    username: aaaa@gmail.com
    password: aaaa aaaa aaaa aaaa # Senha de app
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

email:
  sender: "aaaa@gmail.com"

webdriver:
  chrome:
    # Deixe vazio no Linux se tiver instalado via apt.
    # No Windows, passe o caminho via argumento na execução.
    driver-path: ""

steam:
  urls:
    - "https://store.steampowered.com/wishlist/id/paulloestevam/?sort=discount"

scheduler:
  time: "0 0 11 * * *" # Executa todo dia às 09:00

# Filtros
minDiscountPercentage: 74